// Industry constants and type-safe list
export const INDUSTRIES = {
  TELECOMMUNICATIONS: 'Telecommunications',
  ENTERPRISE_APPLICATION_INTEGRATION: 'Enterprise Application Integration',
  FINTECH: 'FinTech',
  AUTOMOTIVE: 'Automotive',
  HEALTHCARE: 'Healthcare',
  INFOTAINMENT: 'Infotainment',
  PUBLIC_INFRASTRUCTURE: 'Public Infrastructure',
  MOBILE_APPLICATION_DEVELOPMENT: 'Mobile Application Development',
  THREE_D_GRAPHICS: '3D Graphics',
  COMPUTER_VISION: 'Computer Vision',
  FINANCE: 'Finance',
  VOIP: 'VoIP',
  OTHER: 'Other'
} as const;

export const INDUSTRY_VALUES = [
  INDUSTRIES.TELECOMMUNICATIONS,
  INDUSTRIES.ENTERPRISE_APPLICATION_INTEGRATION,
  INDUSTRIES.FINTECH,
  INDUSTRIES.AUTOMOTIVE,
  INDUSTRIES.HEALTHCARE,
  INDUSTRIES.INFOTAINMENT,
  INDUSTRIES.PUBLIC_INFRASTRUCTURE,
  INDUSTRIES.MOBILE_APPLICATION_DEVELOPMENT,
  INDUSTRIES.THREE_D_GRAPHICS,
  INDUSTRIES.COMPUTER_VISION,
  INDUSTRIES.FINANCE,
  INDUSTRIES.VOIP,
  INDUSTRIES.OTHER
] as const;

export type Industry = typeof INDUSTRY_VALUES[number];

